"""channel admin and moderator

Revision ID: 66e3dc998d39
Revises: 47af7b12090a
Create Date: 2024-11-11 18:05:56.538860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e3dc998d39'
down_revision: Union[str, None] = '47af7b12090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.add_column('channels', sa.Column('moderator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'users', ['moderator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'moderator_id')
    op.drop_column('channels', 'admin_id')
    # ### end Alembic commands ###
